version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app


